-- Trials and bosses for trial_boss_set_notes (e.g. Kilt cheat sheet) and per-boss tuning.
-- Trash packs are in 18_trial_trash.sql. Source: UESP wiki (Online:Trials, per-trial pages).
-- Verification: ESO Log (esolog.uesp.net) exportJson does not expose trial/boss/zone tables; run scripts/verify_esolog_trials.py. See DATA_SOURCES.md.

INSERT OR IGNORE INTO trials (id, name) VALUES
    (1, 'Cloudrest'),
    (2, 'Sunspire'),
    (3, 'Rockgrove'),
    (4, 'Dreadsail Reef'),
    (5, 'Sanity''s Edge'),
    (6, 'Aetherian Archive'),
    (7, 'Hel Ra Citadel'),
    (8, 'Sanctum Ophidia'),
    (9, 'Maw of Lorkhaj'),
    (10, 'Halls of Fabrication'),
    (11, 'Asylum Sanctorium'),
    (12, 'Kyne''s Aegis'),
    (13, 'Ossein Cage'),
    (14, 'Lucent Citadel');

INSERT OR IGNORE INTO trial_bosses (trial_id, name) VALUES
    (1, 'Olms'),
    (1, 'Yandir'),
    (1, 'Z''Maja'),
    (2, 'Lokkestiiz'),
    (2, 'Yolna'),
    (2, 'Nahviintaas'),
    (3, 'Stonebreaker'),
    (3, 'Oaxiltso'),
    (3, 'Xalvakka'),
    (4, 'Tideborn Taleria'),
    (4, 'Baron Zaudrus'),
    (5, 'The Serpent'),
    (5, 'The Weird'),
    (6, 'The Mage'),
    (6, 'The Warrior'),
    (6, 'The Serpent'),
    (7, 'Ra Kotu'),
    (7, 'Yorick'),
    (7, 'General Nazenaeen'),
    (8, 'Mantikora'),
    (8, 'Tuzalzekh'),
    (8, 'The Serpent'),
    (9, 'Zhaj''hassa the Forgotten'),
    (9, 'Rakkhat'),
    (10, 'The Hunter Killers'),
    (10, 'The Committee'),
    (10, 'Assembly General'),
    (11, 'Saint Olms'),
    (11, 'Saint Felims'),
    (11, 'Saint Llothis'),
    (12, 'Yandir the Butcher'),
    (12, 'Captain Vrol'),
    (12, 'Lord Falgravn'),
    (13, 'Shapers of Flesh'),
    (13, 'Jynorah and Skorkhif'),
    (13, 'Overfiend Kazpian'),
    (14, 'Count Ryelaz and Zilyesset'),
    (14, 'Cavot Agnan'),
    (14, 'Orphic Shattered Shard'),
    (14, 'Xoryn');
